services:
  - type: web
    name: fitness-backend
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn fitness.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false
