# Generated by Django 5.1.8 on 2026-05-10 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_emailotp_options_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(help_text='Upload MP4 video', upload_to='exercise_videos/')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='exercise_thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='exercises', to='accounts.category')),
            ],
            options={
                'ordering': ['title'],
                'permissions': [('can_view_exercise', 'Can view exercise'), ('create_exercise', 'Can create exercise'), ('update_exercise', 'Can update exercise'), ('can_delete_exercise', 'Can delete exercise')],
            },
        ),
        migrations.CreateModel(
            name='ClientWorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('sets', models.PositiveSmallIntegerField(default=1)),
                ('reps', models.PositiveSmallIntegerField(default=1)),
                ('time_per_rep_seconds', models.PositiveSmallIntegerField(default=15, help_text='Seconds per repetition')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order of exercise within the same day')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='accounts.clientprofile')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workouts', to='accounts.trainerprofile')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='fitnessApp.exercise')),
            ],
            options={
                'ordering': ['client', 'day_of_week', 'order'],
                'permissions': [('can_view_workout_plan', 'Can view workout plan'), ('create_workout_plan', 'Can create workout plan'), ('update_workout_plan', 'Can update workout plan'), ('can_delete_workout_plan', 'Can delete workout plan')],
                'unique_together': {('trainer', 'client', 'day_of_week', 'exercise', 'order')},
            },
        ),
    ]
