# Generated by Django 5.1.8 on 2026-05-10 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_emailotp_options_role'),
        ('fitnessApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientKcalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('actual_kcal', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kcal_logs', to='accounts.clientprofile')),
            ],
            options={
                'verbose_name': 'Client Kcal Log',
                'verbose_name_plural': 'Client Kcal Logs',
                'ordering': ['-date'],
                'permissions': [('can_view_kcallog', 'Can view kcal log'), ('create_kcallog', 'Can create kcal log'), ('update_kcallog', 'Can update kcal log'), ('can_delete_kcallog', 'Can delete kcal log')],
                'unique_together': {('client', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyKcalTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('target_kcal', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kcal_targets', to='accounts.clientprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kcal_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Kcal Target',
                'verbose_name_plural': 'Daily Kcal Targets',
                'permissions': [('can_view_kcaltarget', 'Can view kcal target'), ('create_kcaltarget', 'Can create kcal target'), ('update_kcaltarget', 'Can update kcal target'), ('can_delete_kcaltarget', 'Can delete kcal target')],
                'unique_together': {('client', 'day_of_week')},
            },
        ),
    ]
