# Generated by Django 5.1.8 on 2026-05-10 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_emailotp_options_role'),
        ('fitnessApp', '0002_clientkcallog_dailykcaltarget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientHydrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('actual_cups', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydration_logs', to='accounts.clientprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('client', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ClientSleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('actual_hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_logs', to='accounts.clientprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('client', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyHydrationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('target_cups', models.PositiveSmallIntegerField(help_text='Number of cups (glass) of water')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydration_targets', to='accounts.clientprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hydration_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('client', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='DailySleepTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('target_hours', models.DecimalField(decimal_places=1, help_text='Hours of sleep (e.g., 7.5)', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_targets', to='accounts.clientprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sleep_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('client', 'day_of_week')},
            },
        ),
    ]
