# Generated by Django 5.1.8 on 2026-08-31 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clientprofile_preferred_bmi_and_more'),
        ('fitnessApp', '0003_clienthydrationlog_clientsleeplog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterWorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='master_workout_plans', to='accounts.category')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_workout_plans', to='accounts.trainerprofile')),
            ],
            options={
                'verbose_name': 'Master Workout Plan',
                'verbose_name_plural': 'Master Workout Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterWorkoutPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('sets', models.PositiveSmallIntegerField(default=3)),
                ('reps', models.PositiveSmallIntegerField(default=12)),
                ('time_per_rep_seconds', models.PositiveSmallIntegerField(default=15, help_text='Seconds per repetition')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order within the day')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_plan_items', to='fitnessApp.exercise')),
                ('master_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fitnessApp.masterworkoutplan')),
            ],
            options={
                'verbose_name': 'Master Plan Item',
                'verbose_name_plural': 'Master Plan Items',
                'ordering': ['day_of_week', 'order'],
            },
        ),
    ]
