# Generated by Django 5.1.8 on 2026-09-07 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clientprofile_preferred_bmi_and_more'),
        ('fitnessApp', '0004_masterworkoutplan_masterworkoutplanitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=1)),
                ('longest_streak', models.PositiveIntegerField(default=1)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='accounts.clientprofile')),
            ],
            options={
                'verbose_name': 'Client Streak',
                'verbose_name_plural': 'Client Streaks',
            },
        ),
        migrations.CreateModel(
            name='ClientAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='accounts.clientprofile')),
            ],
            options={
                'verbose_name': 'Client Achievement',
                'verbose_name_plural': 'Client Achievements',
                'ordering': ['-unlocked_at'],
                'unique_together': {('client', 'badge_key')},
            },
        ),
    ]
