# Generated by Django 5.1.8 on 2026-09-07 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clientprofile_preferred_bmi_and_more'),
        ('fitnessApp', '0005_clientstreak_clientachievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Personalized Nutrition Plan', max_length=200)),
                ('daily_calorie_target', models.PositiveIntegerField(default=2000)),
                ('protein_grams', models.PositiveIntegerField(default=140)),
                ('carbs_grams', models.PositiveIntegerField(default=220)),
                ('fat_grams', models.PositiveIntegerField(default=65)),
                ('notes', models.TextField(blank=True, help_text='Special coach instructions, hydration guidelines, foods to avoid')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='accounts.clientprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diet_plans', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diet_plans', to='accounts.trainerprofile')),
            ],
            options={
                'verbose_name': 'Client Diet Plan',
                'verbose_name_plural': 'Client Diet Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDietMealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('MID_MORNING', 'Mid-Morning Snack'), ('LUNCH', 'Lunch'), ('EVENING_SNACK', 'Evening Snack'), ('DINNER', 'Dinner'), ('POST_WORKOUT', 'Post-Workout Fuel')], default='BREAKFAST', max_length=20)),
                ('name', models.CharField(help_text='Meal description, e.g. Oatmeal with Whey & Banana', max_length=255)),
                ('time_label', models.CharField(blank=True, help_text='e.g. 7:30 AM', max_length=50)),
                ('calories', models.PositiveIntegerField(default=350)),
                ('protein_grams', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('carbs_grams', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('fat_grams', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('custom_emoji', models.CharField(blank=True, help_text='Optional custom emoji', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='fitnessApp.clientdietplan')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientMealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to='accounts.clientprofile')),
                ('meal_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='fitnessApp.clientdietmealitem')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('client', 'meal_item', 'date')},
            },
        ),
    ]
