# Generated by Django 5.1.8 on 2026-09-16 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clientprofile_preferred_bmi_and_more'),
        ('fitnessApp', '0006_clientdietplan_clientdietmealitem_clientmeallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientworkoutplan',
            name='master_plan',
            field=models.ForeignKey(blank=True, help_text='Master workout plan this entry was assigned from, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_workout_plans', to='fitnessApp.masterworkoutplan'),
        ),
        migrations.AddField(
            model_name='masterworkoutplan',
            name='assigned_clients',
            field=models.ManyToManyField(blank=True, help_text='Clients currently assigned to this master program', related_name='assigned_master_plans', to='accounts.clientprofile'),
        ),
    ]
