# Generated by Django 5.1.8 on 2026-06-16 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_emailotp_options_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.JSONField()),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FatPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fat_percent', models.JSONField()),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='height',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='neck_circumference',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='waist',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='weight',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='bmi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bmi'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='fat_percent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.fatpercent'),
        ),
    ]
