# Generated by Django 5.1.8 on 2026-08-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bmi_fatpercent_clientprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_bmi',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_fat_percent',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_waist',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_weight',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
