# Generated by Django 5.1.8 on 2026-09-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clientprofile_preferred_bmi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
